update libs to laravel 8
elbgoods/ci-test-tools pull request #37
Opened 2020-10-01 10:26 UTC by eisfeuer

2020-10-01 15:14 UTC, Gummibeer requested changes
Breaking Changes bitte nicht während einem Laravel 8 Kompatibilitäts Upgrade und die `composer.lock` gehört nicht zum Package.

2020-10-01 15:14 UTC, Gummibeer commented on composer.json
> +    "friendsofphp/php-cs-fixer": "^2.16",
2.16.1 war absicht wegen PHP7.4 - 4bc1a0ed82a0ccec93d8fac634e40878f4e8263c

2020-10-01 15:14 UTC, Gummibeer commented on composer.json
> +    "jasonmccreary/laravel-test-assertions": "^1.0",
Wäre ein breaking change für alle Bestandsprojekte und damit nicht bestandteil des Laravel 8 upgrades.

2020-10-01 15:14 UTC, Gummibeer commented on src/PHPUnit/TestCase.php
> +    use AdditionalAssertions,
BC in allen existenten Anwendungen.

2020-10-01 15:26 UTC, eisfeuer commented on src/PHPUnit/TestCase.php
> +    use AdditionalAssertions,
Dann machen wir ein major release oder ein fork

2020-10-01 15:30 UTC, Gummibeer commented on src/PHPUnit/TestCase.php
> +    use AdditionalAssertions,
Ist unser package also fork wäre sinnfrei aber ich würde den Laravel 8 support ungern an ein major release knüpfen - sondern beides getrennt releasen.

2020-10-01 15:33 UTC, eisfeuer commented on src/PHPUnit/TestCase.php
> +    use AdditionalAssertions,
https://github.com/jasonmccreary/laravel-test-assertions/blob/v1.0.0/src/Traits/AdditionalAssertions.php
https://github.com/jasonmccreary/laravel-test-assertions/blob/v0.3.0/src/Traits/HttpTestAssertions.php

Methoden und Parameter haben sich nicht geändert. Es sollte dadurch nichts kaputt gehen.

2020-10-01 15:45 UTC, Gummibeer commented on src/PHPUnit/TestCase.php
> +    use AdditionalAssertions,
Doch, weil ich überall die dependency hochziehen muss damit der Trait auch da ist. Alternativ autoload-dev für die Test Assertions hinzufügen.
Stichwort: https://github.com/elbgoods/bestattungsportal/pull/3

2020-11-05 16:08 UTC, Gummibeer commented
replaced by #40

2020-11-05 16:08 UTC, closed without merging